# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
env:
  - GO111MODULE=on
  - GOPROXY=https://goproxy.cn
  - BETA_VERSION=v0.0.6
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    binary: opengauss_exporter
    main: ./cmd/opengauss_exporter/main.go
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - -s -w -X opengauss_exporter/pkg/version.version={{ .Version }} -X opengauss_exporter/pkg/version.gitCommit={{ .ShortCommit }} -X opengauss_exporter/pkg/version.buildTimestamp={{ .Date }} -X opengauss_exporter/pkg/version.gitTagInfo={{ .Tag }}-{{.ShortCommit}}
archives:
  - id: export-archive
    format: zip
    files:
      - og_exporter_default.yaml
      - LICENSE
      - README.md
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
snapshot:
  name_template: "{{ .Env.BETA_VERSION }}-beta-{{.ShortCommit}}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^build:'
      - Merge pull request
      - Merge branch
      - go mod tidy
      - bump version
release:
  disable: true
#nfpms:
#  - id: export-rpm
#    formats:
#      - apk
#      - deb
#      - rpm
#    bindir: /usr/bin