{
 "title": "OpenGauss Database",
 "description": "This dashboard works with opengauss_exporter for prometheus",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "query_result(pg_exporter_last_scrape_duration_seconds)"
   },
   {
    "name": "release",
    "label": "Release",
    "query": "query_result(pg_exporter_last_scrape_duration_seconds{kubernetes_namespace=\"$namespace\"})"
   },
   { "name": "instance", "label": "Instance", "query": "label_values(pg_up, instance)" },
   {
    "name": "datname",
    "label": "Database",
    "query": "label_values(pg_stat_database_tup_fetched{datname!~\"template.*\"},datname)"
   },
   { "name": "mode", "label": "Lock table", "query": "label_values(mode)" }
  ]
 },
 "panels": [
  { "title": "General Counters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Version",
   "type": "singlestat",
   "description": "数据库版本",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "format": "none",
   "valueName": "name",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_static{release=\"$release\", instance=\"$instance\"}",
     "legendFormat": "{{short_version}}"
    }
   ]
  },
  {
   "title": "Start Time",
   "type": "singlestat",
   "description": "数据库运行时间",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "format": "s",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_run_times_run_time{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Current fetch data",
   "type": "singlestat",
   "description": "数据库查询抓取的行数",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "format": "bytes",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(pg_stat_database_tup_fetched{datname=~\"$datname\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Current insert data",
   "type": "singlestat",
   "description": "数据库查询插入的行数",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "format": "bytes",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(pg_stat_database_tup_inserted{release=\"$release\", datname=~\"$datname\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Current update data",
   "type": "singlestat",
   "description": "数据库查询更新的行数",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "format": "bytes",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(pg_stat_database_tup_updated{datname=~\"$datname\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Max Connections",
   "type": "singlestat",
   "description": "数据库最大连接",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "format": "none",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_connections{release=\"$release\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Shared Buffers",
   "type": "singlestat",
   "description": "数据库shared_buffers大小",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "format": "bytes",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_shared_buffers_bytes{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Effective Cache",
   "type": "singlestat",
   "description": "数据库effective_cache大小",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "format": "bytes",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_effective_cache_size_bytes{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Maintenance Work Mem",
   "type": "singlestat",
   "description": "实例maintenance_work_mem大小",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "format": "bytes",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_maintenance_work_mem_bytes{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Work Mem",
   "type": "singlestat",
   "description": "实例work_mem大小",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "format": "bytes",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_work_mem_bytes{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "singlestat",
   "description": "当前事务数,统计提交和回滚xact_commit+xact_rollback",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(pg_stat_database_xact_commit{datname=~\"$datname\", instance=~\"$instance\"}[5m])) + sum(irate(pg_stat_database_xact_rollback{datname=~\"$datname\", instance=~\"$instance\"}[5m]))"
    }
   ]
  },
  {
   "title": "CPU, Memory and File Descriptor Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average CPU Usage",
     "type": "graph",
     "description": "Average user and system CPU time spent in seconds.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(rate(process_cpu_seconds_total{release=\"$release\", instance=\"$instance\"}[5m]) * 1000)",
       "legendFormat": "CPU Time"
      }
     ]
    },
    {
     "title": "Average Memory Usage",
     "type": "graph",
     "description": "Virtual and Resident memory size in bytes, averages over 5 min interval",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "avg(rate(process_resident_memory_bytes{release=\"$release\", instance=\"$instance\"}[5m]))",
       "legendFormat": "Resident Mem"
      },
      {
       "expr": "avg(rate(process_virtual_memory_bytes{release=\"$release\", instance=\"$instance\"}[5m]))",
       "legendFormat": "Virtual Mem"
      }
     ]
    },
    {
     "title": "Open File Descriptors",
     "type": "graph",
     "description": "Number of open file descriptors",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "process_open_fds{release=\"$release\", instance=\"$instance\"}",
       "legendFormat": "Open FD"
      }
     ]
    }
   ]
  },
  { "title": "Database Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Active sessions",
   "type": "graph",
   "description": "当前活动会话",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=~\"$datname\", instance=~\"$instance\"} !=0",
     "legendFormat": "{{datname}}, s: {{state}}"
    }
   ]
  },
  {
   "title": "Idle sessions",
   "type": "graph",
   "description": "空闲会话",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=~\"$datname\", instance=~\"$instance\", state=~\"idle|idle in transaction|idle in transaction (aborted)\"}",
     "legendFormat": "{{datname}}, s: {{state}}"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "description": "事务变更速率. 提交和回退",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_database_xact_commit{instance=\"$instance\", datname=~\"$datname\"}[5m])",
     "legendFormat": "{{datname}} commits"
    },
    {
     "expr": "irate(pg_stat_database_xact_rollback{instance=\"$instance\", datname=~\"$datname\"}[5m])",
     "legendFormat": "{{datname}} rollbacks"
    }
   ]
  },
  {
   "title": "Fetch data (SELECT)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_database_tup_fetched{datname=~\"$datname\", instance=~\"$instance\"}[5m])",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Insert data",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_database_tup_inserted{datname=~\"$datname\", instance=~\"$instance\"}[5m])",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Update data",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_database_tup_updated{datname=~\"$datname\", instance=~\"$instance\"}[5m])",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Return data",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_database_tup_returned{datname=~\"$datname\", instance=~\"$instance\"}[5m])",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Delete data",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_database_tup_deleted{datname=~\"$datname\", instance=~\"$instance\"}[5m])",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_blks_hit{instance=\"$instance\", datname=~\"$datname\"} / (pg_stat_database_blks_read{instance=\"$instance\", datname=~\"$datname\"} + pg_stat_database_blks_hit{instance=\"$instance\", datname=~\"$datname\"})",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Temp File (Bytes)",
   "type": "graph",
   "description": "Total amount of data written to temporary files by queries in this database. All temporary files are counted, regardless of why the temporary file was created, and regardless of the log_temp_files setting.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_database_temp_bytes{instance=\"$instance\", datname=~\"$datname\"}[5m])",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Lock tables",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_lock_count{datname=~\"$datname\", instance=~\"$instance\", mode=~\"$mode\"} != 0",
     "legendFormat": "{{datname}},{{mode}}"
    }
   ]
  },
  {
   "title": "Conflicts/Deadlocks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_database_conflicts{instance=\"$instance\", datname=~\"$datname\"}[5m])",
     "legendFormat": "{{datname}} conflicts"
    },
    {
     "expr": "irate(pg_stat_database_deadlocks{instance=\"$instance\", datname=~\"$datname\"}[5m])",
     "legendFormat": "{{datname}} deadlocks"
    }
   ]
  },
  {
   "title": "Buffers (bgwriter)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_bgwriter_buffers_backend{instance=\"$instance\"}[5m])",
     "legendFormat": "buffers_backend"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_alloc{instance=\"$instance\"}[5m])",
     "legendFormat": "buffers_alloc"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_backend_fsync{instance=\"$instance\"}[5m])",
     "legendFormat": "backend_fsync"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_checkpoint{instance=\"$instance\"}[5m])",
     "legendFormat": "buffers_checkpoint"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_clean{instance=\"$instance\"}[5m])",
     "legendFormat": "buffers_clean"
    }
   ]
  },
  {
   "title": "Checkpoint Stats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 36 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_bgwriter_checkpoint_write_time{instance=\"$instance\"}[5m])",
     "legendFormat": "write_time - Total amount of time that has been spent in the portion of checkpoint processing where files are written to disk."
    },
    {
     "expr": "irate(pg_stat_bgwriter_checkpoint_sync_time{instance=\"$instance\"}[5m])",
     "legendFormat": "sync_time - Total amount of time that has been spent in the portion of checkpoint processing where files are synchronized to disk."
    }
   ]
  },
  { "title": "Transaction", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "TPS Seasonality",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "og:ins:tps{instance=\"$instance\"}",
     "legendFormat": "TPS"
    },
    {
     "expr": "og:ins:tps{instance=\"$instance\"} OFFSET 1d",
     "legendFormat": "TPS -1D"
    },
    {
     "expr": "og:ins:tps{instance=\"$instance\"} OFFSET 2d",
     "legendFormat": "TPS -2D"
    },
    {
     "expr": "sum(og:ins:commits{instance=\"$instance\"})",
     "legendFormat": "Commit"
    },
    {
     "expr": "sum(og:ins:rollbacks{instance=\"$instance\"})",
     "legendFormat": "Rollback"
    }
   ]
  },
  {
   "title": "Prepared Transaction",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_setting_max_prepared_transactions{instance=\"$instance\"} > bool 0"
    }
   ]
  },
  {
   "title": "Locks Limit per xact",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_setting_max_locks_per_transaction{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Rollbacks in 1min",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(pg_stat_database_xact_rollback{instance=\"$instance\"}[1m])",
     "legendFormat": "Rollbacks"
    }
   ]
  },
  {
   "title": "Locks by Category",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "og:ins:xlock{instance=\"$instance\"}",
     "legendFormat": "Exclusive"
    },
    {
     "expr": "og:ins:wlock{instance=\"$instance\"}",
     "legendFormat": "Write"
    },
    {
     "expr": "og:ins:rlock{instance=\"$instance\"}",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Locks",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (mode) (pg_lock_count{instance=\"$instance\"})",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "Xacts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "og:ins:xacts{instance=\"$instance\"}",
     "legendFormat": "Xacts"
    },
    {
     "expr": "og:ins:xacts_avg30m{instance=\"$instance\"}",
     "legendFormat": "µ"
    },
    {
     "expr": "og:ins:xacts_avg30m{instance=\"$instance\"} + og:ins:xacts_sigma{instance=\"$instance\"}",
     "legendFormat": "+σ"
    },
    {
     "expr": "og:ins:xacts_avg30m{instance=\"$instance\"} - og:ins:xacts_sigma{instance=\"$instance\"}",
     "legendFormat": "-σ"
    },
    {
     "expr": "og:ins:xacts_avg30m{instance=\"$instance\"} + 3 * og:ins:xacts_sigma{instance=\"$instance\"}",
     "legendFormat": "+3σ"
    },
    {
     "expr": "og:ins:xacts_avg30m{instance=\"$instance\"} - 3 * og:ins:xacts_sigma{instance=\"$instance\"}",
     "legendFormat": "-3σ"
    }
   ]
  },
  { "title": "Statement", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Session",
   "type": "table",
   "description": "会话",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "pg_active_slowsql_query_runtime{datname=~\"$datname\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Instance Statementes",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (instance,datname,query) (pg_sql_history_n_calls{instance=\"$instance\"})"
    },
    {
     "expr": "max by (query) (pg_sql_history_total_elapse_time{instance=\"$instance\"})"
    },
    {
     "expr": "max by (query) (pg_query_mean_time{instance=\"$instance\"})"
    },
    {
     "expr": "max by (query) (og:query:rt{instance=\"$instance\"})"
    },
    {
     "expr": "max by (query) (rate(pg_sql_history_n_calls{instance=\"$instance\"}[1h]))"
    },
    {
     "expr": "max by (query) (rate(pg_sql_history_total_elapse_time{instance=\"$instance\"}[1h]))"
    }
   ]
  },
  {
   "title": "Statement RT Ranking",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 78 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "topk(32, pg_sql_history_total_elapse_time{instance=\"$instance\"})",
     "legendFormat": "{{ query }}"
    }
   ]
  },
  {
   "title": "Statement Call",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 92 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "og:query:call{instance=\"$instance\"}",
     "legendFormat": "{{ query }}"
    }
   ]
  },
  {
   "title": "Statement RT",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 92 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "og:query:rt{instance=\"$instance\"}",
     "legendFormat": "{{ query }}"
    }
   ]
  }
 ]
}